#!/usr/bin/env bash
set -euo pipefail

# Build a self-contained STAC catalog for GeoParquet assets generated by aggregation.
# - Stages assets from S3 (or local dir) into an output root
# - Runs a Dockerized Python builder to:
#     * move assets into assets/
#     * create items/ and nested subcatalogs for partitions
#     * write collection.json at root

usage() {
  cat <<'EOF'
Usage: build_stac_catalog.sh [options]

Required:
  --collection ID                 STAC collection identifier

Source (choose one):
  --s3-uri S3_URI                 s3://bucket/prefix of aggregated dataset to package
  --local-source-dir DIR          Local directory with Parquet assets to package

General:
  --profile PROFILE               AWS profile (required with --s3-uri)
  --region REGION                 AWS region (defaults from profile when omitted)
  --output-dir DIR                Catalog output root (default: scripts/aggregation/catalog_output)
  --build-opts OPTS               Extra options for `docker build`
  --keep-output                   Do not clean existing --output-dir
  --keep-incoming                 Keep staged 'incoming' folder after build
  --zip-file FILE                 Zip the catalog to FILE (e.g., catalog.zip) after build
  --verbose                       Enable verbose (bash -x)
  --help                          Show this help

STAC metadata additions:
  --stac-item-properties-json FILE       JSON with additional Item properties
  --stac-collection-properties-json FILE JSON with additional Collection properties
EOF
}

ts() { date '+%Y-%m-%dT%H:%M:%S%z'; }
log_info() { echo "[$(ts)] [INFO] $*"; }
log_warn() { echo "[$(ts)] [WARN] $*"; }
log_err()  { echo "[$(ts)] [ERROR] $*" 1>&2; }

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IMAGE_NAME="geo_stac_catalog:latest"

# Defaults
collection=""
s3_uri=""
local_source_dir=""
profile=""
region=""
output_dir="${script_dir}/catalog_output"
build_opts=""
keep_output=0
keep_incoming=0
zip_file=""
verbose=0
stac_item_props=""
stac_collection_props=""

while [ $# -gt 0 ]; do
  case "$1" in
    --collection) collection="$2"; shift 2;;
    --s3-uri) s3_uri="$2"; shift 2;;
    --local-source-dir) local_source_dir="$2"; shift 2;;
    --profile) profile="$2"; shift 2;;
    --region) region="$2"; shift 2;;
    --output-dir) output_dir="$2"; shift 2;;
    --build-opts) build_opts="$2"; shift 2;;
    --keep-output) keep_output=1; shift;;
    --keep-incoming) keep_incoming=1; shift;;
    --zip-file) zip_file="$2"; shift 2;;
    --verbose) verbose=1; shift;;
    --stac-item-properties-json) stac_item_props="$2"; shift 2;;
    --stac-collection-properties-json) stac_collection_props="$2"; shift 2;;
    --help) usage; exit 0;;
    --) shift; break;;
    *) log_err "Unknown option: $1"; usage; exit 2;;
  esac
done

if [[ -z "$collection" ]]; then
  log_err "--collection is required"
  usage
  exit 1
fi

if [[ -z "$s3_uri" && -z "$local_source_dir" ]]; then
  log_err "Provide one of --s3-uri or --local-source-dir"
  usage
  exit 1
fi
if [[ -n "$s3_uri" && -n "$local_source_dir" ]]; then
  log_err "Provide only one of --s3-uri or --local-source-dir"
  usage
  exit 1
fi

if [[ -n "$s3_uri" && -z "$profile" ]]; then
  log_err "--profile is required when using --s3-uri"
  exit 1
fi

if [[ $verbose -eq 1 ]]; then
  set -x
  log_info "Verbose mode enabled"
fi

command -v docker >/dev/null 2>&1 || { log_err "docker not found in PATH"; exit 127; }
if [[ -n "$s3_uri" ]]; then
  command -v aws >/dev/null 2>&1 || { log_err "aws CLI not found in PATH"; exit 127; }
fi

# Resolve paths portably
resolve_path_portable() {
  local in_path="$1"
  if command -v python3 >/dev/null 2>&1; then
    python3 - "$in_path" <<'PY'
import os, sys
p = sys.argv[1]
p = os.path.expandvars(os.path.expanduser(p))
print(os.path.abspath(p))
PY
  else
    case "$in_path" in
      /*) printf '%s\n' "$in_path" ;;
      ~*) printf '%s\n' "${in_path/#\~/$HOME}" ;;
      *)  printf '%s\n' "$(pwd)/$in_path" ;;
    esac
  fi
}

output_dir="$(resolve_path_portable "$output_dir")"
staging_dir="${output_dir}/incoming"

if [[ $keep_output -eq 0 ]]; then
  if [[ -d "$output_dir" ]]; then
    log_info "Cleaning existing output directory: $output_dir"
    rm -rf "$output_dir"
  fi
fi
mkdir -p "$output_dir"

# Determine region from profile if needed
if [[ -n "$s3_uri" ]]; then
  if [[ -z "$region" ]]; then
    region="$(aws configure get region --profile "$profile" 2>/dev/null || true)"
    if [[ -n "$region" ]]; then
      log_info "Using AWS region '${region}' from profile '${profile}'"
    else
      log_warn "AWS region not specified and could not be retrieved from profile '${profile}'"
    fi
  else
    log_info "Using AWS region '${region}'"
  fi
fi

# Stage source into 'incoming'
mkdir -p "$staging_dir"
if [[ -n "$s3_uri" ]]; then
  log_info "Syncing from ${s3_uri} to ${staging_dir}"
  sync_cmd=(aws s3 sync "$s3_uri" "$staging_dir" --delete --profile "$profile")
  if [[ -n "$region" ]]; then
    sync_cmd+=(--region "$region")
  fi
  # Exclude common Athena dirs and hidden markers
  sync_cmd+=(--exclude "*/query_results/*" --exclude "*_athena*/*")
  "${sync_cmd[@]}"
else
  local_source_dir="$(resolve_path_portable "$local_source_dir")"
  if [[ ! -d "$local_source_dir" ]]; then
    log_err "Local source dir not found: $local_source_dir"
    exit 1
  fi
  log_info "Copying local source from ${local_source_dir} to ${staging_dir}"
  # Prefer rsync if available for speed
  if command -v rsync >/dev/null 2>&1; then
    rsync -a --delete "$local_source_dir"/ "$staging_dir"/
  else
    cp -R "$local_source_dir"/. "$staging_dir"/
  fi
fi

# Count staged parquet files
FILE_COUNT=$(find "$staging_dir" -type f -name "*.parquet" | wc -l | awk '{print $1}')
log_info "Staged Parquet files: ${FILE_COUNT}"
if [[ "$FILE_COUNT" -eq 0 ]]; then
  log_warn "No Parquet files found under '${staging_dir}'"
fi

# Build the STAC catalog image
log_info "Building Docker image ${IMAGE_NAME}${build_opts:+ (opts: $build_opts)}"
# shellcheck disable=SC2086
docker build ${build_opts} -f "${script_dir}/Dockerfile.catalog" -t "$IMAGE_NAME" "$script_dir"

# Prepare docker args
docker_args=(-v "${output_dir}":/data)
item_arg=()
coll_arg=()
if [[ -n "$stac_item_props" ]]; then
  resolved_item="$(resolve_path_portable "$stac_item_props")"
  docker_args+=(-v "${resolved_item}":/tmp/item_props.json:ro)
  item_arg=(--item-properties /tmp/item_props.json)
fi
if [[ -n "$stac_collection_props" ]]; then
  resolved_coll="$(resolve_path_portable "$stac_collection_props")"
  docker_args+=(-v "${resolved_coll}":/tmp/collection_props.json:ro)
  coll_arg=(--collection-properties /tmp/collection_props.json)
fi

log_info "Running STAC catalog builder"
docker run --rm \
  "${docker_args[@]}" \
  "$IMAGE_NAME" /data \
  --collection-id "$collection" \
  --source-dir /data/incoming \
  ${item_arg+"${item_arg[@]}"} \
  ${coll_arg+"${coll_arg[@]}"}

if [[ $keep_incoming -eq 0 ]]; then
  log_info "Removing staged incoming directory: ${staging_dir}"
  rm -rf "$staging_dir" || true
fi

if [[ -n "$zip_file" ]]; then
  zip_path="$(resolve_path_portable "$zip_file")"
  log_info "Creating zip package: ${zip_path}"
  (cd "$output_dir" && zip -r -q "$zip_path" .)
  log_info "Zip package created: ${zip_path}"
fi

log_info "STAC catalog built at ${output_dir} (collection.json at root)"

