#!/usr/bin/env bash
#
# view_hull.sh
#
# Description:
#   Launch a Dockerized Python script that renders an interactive HTML map
#   of a hull GeoJSON generated by scripts/hulls/convex_hulls.sh.
#   The map view automatically fits to the hull extent.
#
# Usage:
#   $0 --input PATH_TO_GEOJSON [--output hull_map.html] [--tiles "OpenStreetMap"] [--title "My Hull"]

set -euo pipefail

usage() {
  sed -n '7,999p' "$0"
}

INPUT=""
OUTPUT="hull_map.html"
TILES="OpenStreetMap"
TITLE=""

LONGOPTS=input:,output:,tiles:,title:,help
PARSED_OPTS=$(getopt --options="" --longoptions="$LONGOPTS" --name "$0" -- "$@")
if [ $? -ne 0 ]; then
  usage
  exit 2
fi

eval set -- "$PARSED_OPTS"
while true; do
  case "$1" in
    --input) INPUT="$2"; shift 2;;
    --output) OUTPUT="$2"; shift 2;;
    --tiles) TILES="$2"; shift 2;;
    --title) TITLE="$2"; shift 2;;
    --help) usage; exit 0;;
    --) shift; break;;
    *) echo "Unexpected option: $1"; usage; exit 3;;
  esac
done

if [ -z "$INPUT" ]; then
  echo "[ERROR] --input PATH_TO_GEOJSON is required" >&2
  usage
  exit 1
fi

if [ ! -f "$INPUT" ]; then
  echo "[ERROR] Input file not found: $INPUT" >&2
  exit 1
fi

echo "[INFO] Rendering map from: $INPUT" >&2
echo "[INFO] Output HTML: $OUTPUT" >&2
echo "[INFO] Tiles: $TILES" >&2
if [ -n "$TITLE" ]; then
  echo "[INFO] Title: $TITLE" >&2
fi

# Build command to run inside the container
INNER_CMD="pip install --no-cache-dir shapely folium >/tmp/pip.log && \
python scripts/hulls/visualize_hull.py --input \"$INPUT\" --output \"$OUTPUT\" --tiles \"$TILES\""

if [ -n "$TITLE" ]; then
  INNER_CMD+=" --title \"$TITLE\""
fi

docker run --rm -v "${PWD}":/work -w /work python:3.11-slim bash -lc "$INNER_CMD"

echo "[OK] Map saved to $OUTPUT" >&2
